artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/374241515051575479/5e6b1f0c24944aea8c38d98d453cd14b/artifacts
end_time: 1766206919343
entry_point_name: ''
experiment_id: '374241515051575479'
lifecycle_stage: active
run_id: 5e6b1f0c24944aea8c38d98d453cd14b
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766190775225
status: 3
tags: []
user_id: aronyang
