artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/915740428883931215
creation_time: 1766229080689
experiment_id: '915740428883931215'
last_update_time: 1766229080689
lifecycle_stage: active
name: CatBoost
