artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/338156372689934620/7a357d601c2a48b682d68ccc2413c4bf/artifacts
end_time: 1766169968907
entry_point_name: ''
experiment_id: '338156372689934620'
lifecycle_stage: active
run_id: 7a357d601c2a48b682d68ccc2413c4bf
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766163649993
status: 3
tags: []
user_id: aronyang
