name: env
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/main/
  - https://mirrors.ustc.edu.cn/anaconda/pkgs/free/
  - https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  # # Core dependencies from pyproject.toml
  # - pyyaml
  # - numpy
  # - pandas
  # - mlflow
  # - filelock
  # - redis
  # - dill
  # - fire
  # - ruamel.yaml
  # - python-redis-lock
  # - tqdm
  # - pymongo
  # - loguru
  # - lightgbm
  # - gym
  # - cvxpy
  # - joblib
  # - matplotlib
  # - jupyter
  # - nbconvert
  # - pyarrow
  # - pydantic-settings
  # - setuptools-scm
  # # Development dependencies
  # - pytest
  # - statsmodels
  # # Build dependencies
  # - cython
