benchmark: SH000905
data_handler_config: &id001
  end_time: 2020-08-01
  fit_end_time: 2014-12-31
  fit_start_time: 2008-01-01
  infer_processors:
  - class: Fillna
    kwargs:
      fields_group: feature
  instruments: csi500
  start_time: 2008-01-01
market: csi500
port_analysis_config: &id002
  backtest:
    account: 100000000
    benchmark: SH000905
    end_time: 2020-08-01
    exchange_kwargs:
      close_cost: 0.0015
      deal_price: close
      limit_threshold: 0.095
      min_cost: 5
      open_cost: 0.0005
    start_time: 2017-01-01
  strategy:
    class: TopkDropoutStrategy
    kwargs:
      n_drop: 5
      signal:
      - <MODEL>
      - <DATASET>
      topk: 50
    module_path: qlib.contrib.strategy
qlib_init:
  provider_uri: ~/.qlib/qlib_data/cn_data
  region: cn
task:
  dataset:
    class: DatasetH
    kwargs:
      handler:
        class: Alpha158
        kwargs: *id001
        module_path: qlib.contrib.data.handler
      segments:
        test:
        - 2017-01-01
        - 2020-08-01
        train:
        - 2008-01-01
        - 2014-12-31
        valid:
        - 2015-01-01
        - 2016-12-31
    module_path: qlib.data.dataset
  model:
    class: StackingModel
    kwargs:
      base_estimator: lightgbm
      n_estimators: 5
      n_jobs: 6
      verbose: 1
      lightgbm:
        loss: mse
        colsample_bytree: 0.8879
        learning_rate: 0.2
        subsample: 0.8789
        reg_alpha: 205.6999
        reg_lambda: 580.9768
        max_depth: 8
        num_leaves: 210
        num_threads: 20
        verbose: -1
    module_path: qlib.contrib.model.stacking
  record:
  - class: SignalRecord
    kwargs:
      dataset: <DATASET>
      model: <MODEL>
    module_path: qlib.workflow.record_temp
  - class: SigAnaRecord
    kwargs:
      ana_long_short: false
      ann_scaler: 252
    module_path: qlib.workflow.record_temp
  - class: PortAnaRecord
    kwargs:
      config: *id002
    module_path: qlib.workflow.record_temp
