artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/0
creation_time: 1765797653212
experiment_id: '0'
last_update_time: 1765797653212
lifecycle_stage: active
name: Default
