artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/262320942300307503
creation_time: 1766170038610
experiment_id: '262320942300307503'
last_update_time: 1766170038610
lifecycle_stage: active
name: Transformer
