artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/415215297032677806/cc6b0d58fa4742988a26f6b27deb0f02/artifacts
end_time: 1766448716132
entry_point_name: ''
experiment_id: '415215297032677806'
lifecycle_stage: active
run_id: cc6b0d58fa4742988a26f6b27deb0f02
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766448671192
status: 3
tags: []
user_id: aronyang
