artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/576147767690328835/c2a9c0e4bee64efdbf1fe296d05989f4/artifacts
end_time: 1766449001351
entry_point_name: ''
experiment_id: '576147767690328835'
lifecycle_stage: active
run_id: c2a9c0e4bee64efdbf1fe296d05989f4
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766448992407
status: 4
tags: []
user_id: aronyang
