artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/842672011423065337/f63dbe3d195c4d80a91447816b29a8f8/artifacts
end_time: 1765836567759
entry_point_name: ''
experiment_id: '842672011423065337'
lifecycle_stage: active
run_id: f63dbe3d195c4d80a91447816b29a8f8
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1765834485107
status: 3
tags: []
user_id: aronyang
