artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/915740428883931215/27d25263cadc4b9386a0f996a9db3e7d/artifacts
end_time: 1766229168022
entry_point_name: ''
experiment_id: '915740428883931215'
lifecycle_stage: active
run_id: 27d25263cadc4b9386a0f996a9db3e7d
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766229080918
status: 3
tags: []
user_id: aronyang
