artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/402705636510509710
creation_time: 1765801797567
experiment_id: '402705636510509710'
last_update_time: 1765801797567
lifecycle_stage: active
name: Sandwich
