artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/175922105682590244/ae133b8877cf4c28ae4c93516f11decd/artifacts
end_time: 1766586623249
entry_point_name: ''
experiment_id: '175922105682590244'
lifecycle_stage: active
run_id: ae133b8877cf4c28ae4c93516f11decd
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766586563936
status: 3
tags: []
user_id: aronyang
