artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/833966254515411119/211e8bc06521484ab7d0212a9c9b2ea8/artifacts
end_time: 1766282082615
entry_point_name: ''
experiment_id: '833966254515411119'
lifecycle_stage: active
run_id: 211e8bc06521484ab7d0212a9c9b2ea8
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766282049442
status: 4
tags: []
user_id: aronyang
