artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/514649467073052901/c94cd9e45ef44fe4a3f0c1b9e0c3fc88/artifacts
end_time: 1766180482275
entry_point_name: ''
experiment_id: '514649467073052901'
lifecycle_stage: active
run_id: c94cd9e45ef44fe4a3f0c1b9e0c3fc88
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766174079142
status: 3
tags: []
user_id: aronyang
