artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/391279676166188719
creation_time: 1766412553575
experiment_id: '391279676166188719'
last_update_time: 1766412553575
lifecycle_stage: active
name: Transformer
