artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/301629261432114046/0220de1cbae744d48aed2a9ef0355404/artifacts
end_time: 1766554082336
entry_point_name: ''
experiment_id: '301629261432114046'
lifecycle_stage: active
run_id: 0220de1cbae744d48aed2a9ef0355404
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766551081387
status: 3
tags: []
user_id: aronyang
