artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/402705636510509710/09341f2ec10e4b05ae68bdcbb2a8c2c9/artifacts
end_time: 1765834482703
entry_point_name: ''
experiment_id: '402705636510509710'
lifecycle_stage: active
run_id: 09341f2ec10e4b05ae68bdcbb2a8c2c9
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1765831148270
status: 3
tags: []
user_id: aronyang
