artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/359097524621352841
creation_time: 1766376896566
experiment_id: '359097524621352841'
last_update_time: 1766376896566
lifecycle_stage: active
name: Localformer
