artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/415215297032677806
creation_time: 1766412503653
experiment_id: '415215297032677806'
last_update_time: 1766412503653
lifecycle_stage: active
name: XGBoost
