artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/544565763195565929/1e729a528c9a4207be584502f3f8d43c/artifacts
end_time: 1766229338632
entry_point_name: ''
experiment_id: '544565763195565929'
lifecycle_stage: active
run_id: 1e729a528c9a4207be584502f3f8d43c
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766229170158
status: 3
tags: []
user_id: aronyang
