artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/842672011423065337/ed83cb7319394bc8aaf73f84d68da300/artifacts
end_time: null
entry_point_name: ''
experiment_id: '842672011423065337'
lifecycle_stage: active
run_id: ed83cb7319394bc8aaf73f84d68da300
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1765818982598
status: 1
tags: []
user_id: aronyang
