artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/760287638203147465/27b29ce004c6442b909cd674c8abfb7d/artifacts
end_time: 1766583700173
entry_point_name: ''
experiment_id: '760287638203147465'
lifecycle_stage: active
run_id: 27b29ce004c6442b909cd674c8abfb7d
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766581559597
status: 3
tags: []
user_id: aronyang
