artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/175922105682590244
creation_time: 1766470821688
experiment_id: '175922105682590244'
last_update_time: 1766470821688
lifecycle_stage: active
name: CatBoost
