artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/833966254515411119/eca3f3d0f2ac4bf488f1715b1f071367/artifacts
end_time: 1766394718383
entry_point_name: ''
experiment_id: '833966254515411119'
lifecycle_stage: active
run_id: eca3f3d0f2ac4bf488f1715b1f071367
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766377215589
status: 3
tags: []
user_id: aronyang
