experiment:
  name: estimator_example
  observer_type: file_storage
  mode: train

model:
    module_path: qlib.contrib.model.pytorch_nn
    class: DNNModelPytorch
    args:
        loss: mse
        input_dim: 158
        output_dim: 1
        lr: 0.002
        lr_decay: 0.96
        lr_decay_steps: 100
        optimizer: 'adam'
        max_steps: 8000
        batch_size: 4096
        GPU: '0'
data:
  class: Alpha158
  args:
    dropna_label: True
    dropna_feature: True
  filter:
    market: csi300
trainer:
  class: StaticTrainer
  args:
    train_start_date: 2007-01-01
    train_end_date: 2014-12-31
    validate_start_date: 2015-01-01
    validate_end_date: 2016-12-31
    test_start_date: 2017-01-01
    test_end_date: 2020-08-01
strategy:
  class: TopkDropoutStrategy
  args:
    topk: 50
    n_drop: 5
backtest:
  normal_backtest_args:
    verbose: False
    limit_threshold: 0.095
    account: 100000000
    benchmark: SH000300
    deal_price: close
    open_cost: 0.0005
    close_cost: 0.0015
    min_cost: 5
  long_short_backtest_args:
    topk: 50

qlib_data:
  # when testing, please modify the following parameters according to the specific environment
  provider_uri: "~/.qlib/qlib_data/cn_data"
  region: "cn"
