artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/394221449900351772
creation_time: 1766470773025
experiment_id: '394221449900351772'
last_update_time: 1766470773025
lifecycle_stage: active
name: LightGBM
