artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/956890857305726521/60c3fb7761c449ef9da27d67f3d403c9/artifacts
end_time: 1766190772717
entry_point_name: ''
experiment_id: '956890857305726521'
lifecycle_stage: active
run_id: 60c3fb7761c449ef9da27d67f3d403c9
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766187472133
status: 3
tags: []
user_id: aronyang
