artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/576147767690328835
creation_time: 1766412705798
experiment_id: '576147767690328835'
last_update_time: 1766412705798
lifecycle_stage: active
name: DoubleEnsemble
