artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/816539570393037524
creation_time: 1766169971572
experiment_id: '816539570393037524'
last_update_time: 1766169971572
lifecycle_stage: active
name: XGBoost
