artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/833966254515411119/be51cbe4ca49469489c1bc3124299b85/artifacts
end_time: 1766376028632
entry_point_name: ''
experiment_id: '833966254515411119'
lifecycle_stage: active
run_id: be51cbe4ca49469489c1bc3124299b85
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766361728990
status: 3
tags: []
user_id: aronyang
