artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/223882311976452013
creation_time: 1766180484526
experiment_id: '223882311976452013'
last_update_time: 1766180484526
lifecycle_stage: active
name: DoubleEnsemble
