artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/833966254515411119/7ff5318fa521479ea8be7c0f0bc47c72/artifacts
end_time: null
entry_point_name: ''
experiment_id: '833966254515411119'
lifecycle_stage: active
run_id: 7ff5318fa521479ea8be7c0f0bc47c72
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766448579118
status: 1
tags: []
user_id: aronyang
