artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/842672011423065337
creation_time: 1765818982340
experiment_id: '842672011423065337'
last_update_time: 1765818982340
lifecycle_stage: active
name: Localformer
