artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/301629261432114046/03acba569b1542f1918a0dd38f4b5dd7/artifacts
end_time: 1766408638537
entry_point_name: ''
experiment_id: '301629261432114046'
lifecycle_stage: active
run_id: 03acba569b1542f1918a0dd38f4b5dd7
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766405570900
status: 3
tags: []
user_id: aronyang
