artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/576147767690328835/66494665a8cf44bebc9829658107ce2d/artifacts
end_time: 1766412980786
entry_point_name: ''
experiment_id: '576147767690328835'
lifecycle_stage: active
run_id: 66494665a8cf44bebc9829658107ce2d
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766412705971
status: 3
tags: []
user_id: aronyang
