artifact_location: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/619788161733375442
creation_time: 1766224134726
experiment_id: '619788161733375442'
last_update_time: 1766224134726
lifecycle_stage: active
name: LightGBM
