artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/391279676166188719/954a1dc2004b4944bebf21e09c3d3747/artifacts
end_time: 1766412653702
entry_point_name: ''
experiment_id: '391279676166188719'
lifecycle_stage: active
run_id: 954a1dc2004b4944bebf21e09c3d3747
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766412553747
status: 3
tags: []
user_id: aronyang
