market: &market all
benchmark: &benchmark SPY
filter_instruments: &filter_instruments ^(GLD|SHV|AGG|BNDX|QQQ|EEMX|EEMA|VNQ|VAW|PXE|IRBO|XME|SMH|ICLN|IPAY|XT|VGT|LIT|UVXY|DOG)$
filter_start_time: &filter_start_time 2007-01-01
filter_end_time: &filter_end_time 2021-12-31
fit_start_time: &fit_start_time 2007-01-01
fit_end_time: &fit_end_time 2016-12-31
val_start_time: &val_start_time 2017-01-01
val_end_time: &val_end_time 2019-12-31
test_start_time: &test_start_time 2020-01-01
test_end_time: &test_end_time 2022-10-31

datahandler: &datahandler Alpha360

qlib_init:
    provider_uri: "~/.qlib/qlib_data/us_data"
    region: us

data_handler_config: &data_handler_config
    start_time: *filter_start_time
    end_time: *filter_end_time
    fit_start_time: *fit_start_time
    fit_end_time: *fit_end_time
    instruments: *market
    filter_pipe:
      - filter_type: NameDFilter
        name_rule_re: *filter_instruments
        filter_start_time: *filter_start_time
        filter_end_time: *filter_end_time
    infer_processors:
      - class: RobustZScoreNorm
        kwargs:
          fields_group: feature
          clip_outlier: true
      - class: Fillna
        kwargs:
          fields_group: feature
    learn_processors:
      - class: CSRankNorm
        kwargs:
          fields_group: label
    label: ["Ref($close, -2) / Ref($close, -1) - 1"]

port_analysis_config: &port_analysis_config
    executor: 
        class: SimulatorExecutor
        module_path: qlib.backtest.executor
        kwargs: 
            time_per_step: day
            generate_portfolio_metrics: True
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy
        kwargs:
            signal:
                - <MODEL> 
                - <DATASET>
            topk: 10
            n_drop: 1
    backtest:
        start_time: *test_start_time
        end_time: *test_end_time
        account: 100000000
        benchmark: *benchmark
        exchange_kwargs:
            limit_threshold: 0.095
            deal_price: close
            open_cost: 0.0005
            close_cost: 0.0015
            min_cost: 5
            
task:
    model:
        class: GRU
        module_path: qlib.contrib.model.pytorch_gru
        kwargs:
            d_feat: 6
            hidden_size: 64
            num_layers: 2
            dropout: 0.0
            n_epochs: 200
            lr: 1e-3
            early_stop: 20
            batch_size: 800
            metric: loss
            loss: mse
            GPU: 0
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
               class: *datahandler
               module_path: qlib.contrib.data.handler
               kwargs: *data_handler_config
            segments:
               train: [*fit_start_time, *fit_end_time]
               valid: [*val_start_time, *val_end_time]
               test: [*test_start_time, *test_end_time]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            model: <MODEL>
            dataset: <DATASET>
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
