artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/402705636510509710/a9c29a97433c4fb289b7a073a730cd25/artifacts
end_time: 1766157481307
entry_point_name: ''
experiment_id: '402705636510509710'
lifecycle_stage: active
run_id: a9c29a97433c4fb289b7a073a730cd25
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766152692536
status: 3
tags: []
user_id: aronyang
