artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/415215297032677806/1bf559112cb7434fb9145a638cde8dc8/artifacts
end_time: 1766412551562
entry_point_name: ''
experiment_id: '415215297032677806'
lifecycle_stage: active
run_id: 1bf559112cb7434fb9145a638cde8dc8
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766412503912
status: 3
tags: []
user_id: aronyang
