name: Pull Request Labels
on: pull_request
jobs:
  example_comment_pr:
    permission: write-all
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: /
            Hello World
          reactions: eyes, rocket
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
