name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-labels.outputs.status }}
    steps:
      - id: check-labels
        uses: mheap/github-action-required-labels@v2
        with:
          mode: exactly
          count: 1
          labels: "bug, documentation, enhancement"
          add_comment: true
          exit_type: success
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  do-other:
    runs-on: ubuntu-latest
    needs: label
    steps:
      - run: echo needs.label.outputs.status
