name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      # This step is necessary because the lint title uses the .commitlintrc.js file in the project root directory.
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'

      - name: Install commitlint
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Validate PR Title with commitlint
        env:
          BODY: ${{ github.event.pull_request.title }}
        run: |
          printf '%s\n' "$BODY" | npx --no-install commitlint --config .commitlintrc.js
