name: Lint pull request title

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-title:
    runs-on: ubuntu-latest
    steps:
      # This step is necessary because the lint title uses the .commitlintrc.js file in the project root directory.
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: '22'

      - name: Install commitlint
        run: npm ci --ignore-scripts --no-audit --no-fund

      - name: Validate PR Title with commitlint
        env:
          BODY: ${{ github.event.pull_request.title }}
        run: |
          printf '%s\n' "$BODY" | npx --no-install commitlint --config .commitlintrc.js
