artifact_uri: file:///Users/aronyang/Documents/GitHub/qlib/examples/run_all_model_records/841570927585565671/f9b17ac05c144fb1acece54e26be1168/artifacts
end_time: 1766412703407
entry_point_name: ''
experiment_id: '841570927585565671'
lifecycle_stage: active
run_id: f9b17ac05c144fb1acece54e26be1168
run_name: mlflow_recorder
source_name: ''
source_type: 4
source_version: ''
start_time: 1766412656151
status: 3
tags: []
user_id: aronyang
